# Generated by Django 4.0.3 on 2023-01-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.BooleanField(blank=True, default=False)),
                ('custom_bits', models.CharField(blank=True, max_length=256)),
                ('bit_size', models.IntegerField(blank=True)),
                ('fixed_sequence', models.BooleanField(blank=True, default=False)),
                ('fixed_size', models.IntegerField(blank=True)),
                ('fixed_freq', models.IntegerField(blank=True)),
                ('pos_logic', models.BooleanField(blank=True, default=True)),
                ('scheme_choice', models.CharField(choices=[('Unipolar', 'Unipolar'), ('NRZ-L', 'NRZ-L'), ('NRZ-I', 'NRZ-I'), ('Polar RZ', 'Polar RZ'), ('Manchester', 'Manchester'), ('Differential Manchester', 'Differential Manchester'), ('AMI', 'AMI')], default='Unipolar', max_length=50)),
                ('scrambling_choice', models.CharField(blank=True, choices=[('None', 'None'), ('B8ZS', 'B8ZS'), ('HDB3', 'HDB3')], default='None', max_length=20)),
            ],
        ),
    ]
